### ISSUE TITLE
Use of undeclared type 'B68UIFloatLabelTextField'

### ISSUE THREAD

**Issue by schan93** [dirkfabisch/B68FloatingLabelTextField#1]
Hi, I recently stumbled upon your customized Text Field and I wanted to see how it works. However, I can't seem to make it work in my project as I get an error saying `Use of undeclared type 'B68UIFloatLabelTextField'` when I try to make an `IBOutlet` of this type. I installed the project via `Cocoapods` which worked and tried to follow your example but I can't seem to get this working. If it helps I'm making a Swift project. Do I need to import anything or add the file anywhere? Thanks for your help.

**Comment by dirkfabisch** [comment]
Hi @schan93 
did you import the module in your swift file?
