### ISSUE TITLE
Cant use it with init()

### ISSUE THREAD

**Issue by syedhassan** [dirkfabisch/B68FloatingLabelTextField#5]
Hi,

I am trying to use your pod but not able to lazy load it..

I am not able to do 
var textField = B68UIFloatLabelTextField()

but I had to do
var textField = B68UIFloatLabelTextField(coder: NSCoder.empty())

and further had to write an extension of 

extension NSCoder {
    class func empty() -> NSCoder {
        let data = NSMutableData()
        let archiver = NSKeyedArchiver(forWritingWithMutableData: data)
        archiver.finishEncoding()
        return NSKeyedUnarchiver(forReadingWithData: data)
    }
}

Can you please update it to use the default init method

**Comment by dirkfabisch** [comment]
This is on purpose. Please the use `init(frame:)`. This is consistent with the default text label.

**Comment by syedhassan** [comment]
Can you share an example.

I am tryind to do

var field:B68UIFloatLabelTextField = B68UIFloatLabelTextField()

but I never see the option of frame init method at all!

Sharing my screengrab http://cl.ly/image/1Q2C1V2U1x2R
